[package]
name = "Naloga3"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
union-find = "0.4.3"

[profile.release]
opt-level = 3          # Maximum optimization
lto = "fat"           # Link-time optimization
codegen-units = 1     # Better optimization at cost of compile time

